name: CI
on: push

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Yarn Install
        run: yarn
      - name: Test
        run: yarn test
      - name: Compile
        run: yarn compile
      - name: Ensure compiled/index.js is in sync with sources
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Please run yarn compile before commit."
            exit 1
          else
            echo "Things are in sync!"
          fi
